# This is a basic workflow to help you get started with Actions

name: package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - dev-0.9.1
  pull_request:
    branches:
    - dev-0.9.1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: dev-0.9.1

    # install yaml
    - name: update composer
      run: |
        cd /home/runner/work/iRime-Resource/iRime-Resource/script/package
        composer update

    - name: run package script
      env:
        ACCESSKEYID: ${ { secrets.ACCESSKEYID } }
        ACCESSKEYSECRET:  ${{secrets.ACCESSKEYSECRET}}
        ENDPOINT:  ${ { secrets.ENDPOINT }}
        BUCKET:  ${ { secrets.BUCKET }}
        UPLOADSCHEMAURL:  ${ { secrets.UPLOADSCHEMAURL } }
      run: php /home/runner/work/iRime-Resource/iRime-Resource/script/package/package.php
